version: "3.8"
services:
  database:
    image: mongo
    restart: always
    volumes:
      - volume:/data/db

  database-seed:
    build:
      context: ./database_seed
      dockerfile: Dockerfile
    depends_on:
      - database
  
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - /node_modules
      - ./node-web:/app
    ports:
      - "5000:5000"

volumes:
  volume:
